config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :spots do
    collection do
      get 'search'
    end
  end
  resources :users, only:[:show, :destroy]

  get '/policy', to: 'application#policy'
  get '/use', to: 'application#use'
  
  # Defines the root path route ("/")
  root to: "spots#index"

end

app/models/spot.rb
class Spot < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one_attached :photo
  belongs_to :user
  belongs_to :category, class_name: 'Category'
  validates :lat, :lng, :name, presence: true
  validates :category_id, numericality: { other_than: 1, message: "can't be blank" } 
  before_validation :resize_photo

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "lat", "lng", "name", "spots_url", "updated_at", "user_id", "value"]
  end

  private
  def resize_photo
    return unless photo.attached?
  
    begin
      # アップロードされた画像を取得
      image = MiniMagick::Image.read(photo.download)
      image.resize "300x300"
  
      # 元の画像を削除し、新しいリサイズ済みの画像を保存
      photo.attach(
        io: StringIO.new(image.to_blob),
        filename: photo.filename.to_s,
        content_type: photo.content_type
      )
    rescue StandardError => e
      Rails.logger.error "Image resizing failed: #{e.message}"
    end
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  
  before_action :set_spot, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :update,:destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]

  # GET /spots
  def index
    @q = Spot.ransack(params[:q])
    @params = params

    if params[:q] && (params[:q][:name_cont].present? || params[:q][:category_id_eq].present?)
      @spots = @q.result(distinct: true).includes(:user).order("created_at DESC")
    else
      @spots = Spot.includes(:user).order("created_at DESC")
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /spots/1
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  def create
    @spot = Spot.new(spot_params)

    unless @spot.photo.attached?
      @spot.photo.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'image.png')), filename: 'image.png', content_type: 'image/png')
    end

    if @spot.save
      redirect_to @spot, notice: "Spot was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /spots/1
  def update
    if @spot.update(spot_params)
      redirect_to @spot, notice: "Spot was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /spots/1
  def destroy
    @spot.destroy
    redirect_to spots_url, notice: "Spot was successfully destroyed.", status: :see_other
  end

  def search
    @q = Spot.ransack(params[:q])
    @params = params
    @spots = @q.result.includes(:user).order("created_at DESC")
    render 'index'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      #@spot = Spot.find(params[:id])
      @spot = Spot.find_by(id: params[:id])
      unless @spot
        flash[:error] = "Spot not found"
        redirect_to spot_path
      end
    end

    # Only allow a list of trusted parameters through.
    def spot_params
      params.require(:spot).permit(:lat, :lng, :name, :photo, :category_id, :value, :spots_url).merge(user_id: current_user.id)
    end

    def move_to_index
      unless user_signed_in?
        redirect_to action: :index
      end
    end

    def authorize_user!
      unless @spot.user == current_user
        flash[:alert] = "You don't have permission to edit this spot."
        redirect_to root_path
      end
    end

end

app/helpers/spots_helper.rb
module SpotsHelper
  def marker_content(spot)
    html = ""
    html << <<-HTML
    <div class="spot-category #{'background-category1' if spot.category.name == '農園'} #{'background-category2' if spot.category.name == '産直店'} #{'background-category3' if spot.category.name == '園芸店'} #{'background-category4' if spot.category.name == 'レストラン'}">
      #{spot.category.name}
    </div>
    HTML
    html << "#{link_to spot.name, spot_path(spot)}<br />"
    if spot.photo.attached?
      html << "#{link_to(image_tag(spot.photo, width: '100%'), spot_path(spot))}<br />"
    end
    return html.html_safe
  end
end

app/views/spots/_form.html.erb
<%= form_with(model: spot) do |form| %>
  <% if spot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new-form-wrap">
    <div class="new_form_1">
      <div class="message">
          <span><%= image_tag("tomato.png", class:"tomato-icon") %></span>マップより登録場所をタップ
      </div>
      <div class="lat">
        <%= form.text_field :lat, readonly: true, class: "block" %>
      </div>
      <div class="lng">
        <%= form.text_field :lng, readonly: true, class: "block" %>
      </div>
    </div>

    <div id="map" style="height:350px;" data-geolocate-control="on"></div>

    <div class="new_form_2">
        <%#= form.label :"写真など", style: "display: block" %>
        <%= form.file_field :photo, readonly: false %>
    </div>

    <div class="new_form_3">
      <div class="name">
        <div class="message">
          <span><%= image_tag("tomato.png", class:"tomato-icon") %></span>名前
        </div>
        <%= form.text_field :name, readonly: false, class:"block-name" %>
      </div>
      <div class="category">
        <div class="message">
          <span><%= image_tag("tomato.png", class:"tomato-icon") %></span>カテゴリ選択
        </div>
        <%= form.collection_select(:category_id, Category.all, :id, :name, { include_blank: '---' }, {class:"category-select"}) %>
      </div>
    </div>

    <div class="new_form_4">
      <div class="message">
          コメント
      </div>
      <%= form.text_area  :value, readonly: false, class:"block-text" %>
    </div>

    <div class="new_form_5">
      <%= form.label :"URL", style: "display: block" %>
      <%= form.text_field :spots_url, readonly: false, class:"block-name" %>
    </div>
      
    <div class="btn">
      <%= form.submit "登録", class: "btn btn-success" %>
    </div>
  </div>

<% end %>

<script>
document.addEventListener('turbo:load', () => {
  const center = <%= spot.new_record? ? [139.7673068, 35.6809591] : [spot.lng, spot.lat] %>
  const map = new geolonia.Map({
    container: 'map',
    center: center,
    zoom: <%= spot.new_record? ? 14 : 16 %>
  })
  const marker = new geolonia.Marker()

  <% if !spot.new_record? %>
  marker.setLngLat(center).addTo(map)
  <% end %>

  function onClick(e) {
    const lngLat = e.lngLat

    if (marker) {
      marker.remove()
    }

    marker.setLngLat([lngLat.lng, lngLat.lat]).addTo(map)
    document.querySelector("#spot_lng").value = lngLat.lng
    document.querySelector("#spot_lat").value = lngLat.lat
  }

  map.on('click', onClick)
})
</script>

app/views/spots/_spot.html.erb
<div id="<%= dom_id spot %>" class="spot-card">
  <!-- カード上部（カテゴリー帯＋タイトル） -->
  <div class="spot-card-header">
    <div class="spot-category <%= 
      case spot.category.name
      when '農園' then 'background-category1'
      when '産直店' then 'background-category2'
      when '園芸店' then 'background-category3'
      when 'レストラン' then 'background-category4'
      when 'アウトドア' then 'background-category5'
      else ''
      end
    %>">
      <%= spot.category.name %>
    </div>

    <div class="spots-name">
      <%= link_to spot.name, spot_path(spot) %>
    </div>
  </div>

  <!-- カード本文（画像など） -->
  <div class="spot-card-body">
    <% if spot.photo.present? %>
      <div class="spot-thumbnail">
        <%= link_to spot do %>
          <%= image_tag spot.photo, class: "spot-image" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/spots/edit.html.erb
<%= render "shared/header" %>
<div class="container">
  <h2 class="H2">編集</h2>

  <%= render "form", spot: @spot %>

    <%= link_to(spot_path,class: "purchase-btn") do %>
      <span class="purchase-btn-text">戻る</span>
      <%= image_tag "back.png", size: "185x50", class: "purchase-btn-icon" %>
    <% end %>

  <script type="text/javascript" src="https://cdn.geolonia.com/v1/embed?geolonia-api-key=<%= ENV['MAP_API_KEY'] %>"></script>
</div>

app/views/spots/index.html.erb
<%= render "shared/header" %>

<div class="map-container" data-controller="sidebar">
  <!-- ▼ スライドサイドバー (初期状態は非表示) ▼ -->
  <div class="sidebar" id="sidebar" data-sidebar-target="sidebar">
    <div class="sidebar-inner">
      <!-- ▼ 検索フォーム、一覧 ▼ -->
      <%= search_form_for @q, url: search_spots_path, html: { id: "detailed-search-form" }, method: :get do |f| %>
        <div class="search-field-container">
          <div class="search-field">
            <%= f.text_field :name_cont, placeholder: ' キーワードで探す', class: "search-field-input" %>
          </div>
          <div class="search-field">
            <%= select_tag "q[category_id_eq]",
                options_for_select(Category.all.map { |c| [c.name, c.id] }, params[:q]&.[](:category_id_eq)),
                include_blank: "カテゴリで探す",
                class: "search-field-select"
            %>
          </div>
        </div>
        <div class="search-btn-field-container">
          <div class="search-btn-field">
            <%= f.submit "検索", class: "search-btn", id: "search-button" %>
          </div>
          <button class="clear-btn">
            <%= link_to "クリア", spots_path, class: "clear-btn-name" %>
          </button>
        </div>
      <% end %>

      <div id="spots">
        <% @spots.in_groups_of(3, false) do |spot_group| %>
          <div class="row">
            <% spot_group.each do |spot| %>
              <div class="spot-list-item">
                <%= render spot %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <!-- ▲ 検索フォーム、一覧 ▲ -->
  </div>
  <!-- ▲ スライドサイドバー ▲ -->

  <!-- ▼ メインコンテンツ (地図表示) ▼ -->
  <div class="map-wrap">
    <!-- サイドバー開閉トグルボタンを画面上部に配置（例） -->
    <button class="toggle-btn" id="toggleSidebarBtn" data-action="click->sidebar#toggle">メニュー</button>

    <% if @params[:q] %>
      <div class="geolonia"
        data-geojson="/spots.json?q[name_cont]=<%= @params['q']['name_cont'] %>&q[category_id_eq]=<%= @params['q']['category_id_eq'] %>"
        data-geolocate-control="on">
      </div>
    <% else %>
      <div class="geolonia"
        data-geojson="/spots.json"
        data-geolocate-control="on">
      </div>
    <% end %>
    <div class="new-spot-btn">
      <%= link_to(new_spot_path, class: "purchase-btn") do %>
        <span class="purchase-btn-text">登録する</span>
        <%= image_tag "icon_new.png", size: "185x50", class: "purchase-btn-icon" %>
      <% end %>
    </div>
  </div>
  <!-- ▲ メインコンテンツ ▲ -->
</div>

<script type="text/javascript" src="https://cdn.geolonia.com/v1/embed?geolonia-api-key=<%= ENV['MAP_API_KEY'] %>"></script>

app/views/spots/new.html.erb
<%= render "shared/header" %>
<div class="container" data-controller="confirm-leave">
  <h2 class="H2">新規スポット登録</h2>
  <p class="required"><span><%= image_tag("tomato.png", class:"tomato-icon") %></span>は必須項目です</p>

  <%= render "form", spot: @spot %>

  <br>

    <%= link_to(root_path, class: "purchase-btn", data: { action: "click->confirm-leave#confirmHome" }) do %>
      <span class="purchase-btn-text">HOMEへ</span>
      <%= image_tag "home.png", size: "185x50", class: "purchase-btn-icon" %>
    <% end %>

  <script type="text/javascript" src="https://cdn.geolonia.com/v1/embed?geolonia-api-key=<%= ENV['MAP_API_KEY'] %>"></script>
</div>

app/views/spots/show.html.erb
<%= render "shared/header" %>
<div class="container">

  <h2 class="H2">登録内容の詳細</h2>

  <%= form_with(model: @spot, local: true) do |form| %>
    <div class="spot-category <%=
      case @spot.category.name
      when '農園' then 'background-category1'
      when '産直店' then 'background-category2'
      when '園芸店' then 'background-category3'
      when 'レストラン' then 'background-category4'
      when 'アウトドア' then 'background-category5'
      else ''
      end
    %>">
      <%= @spot.category.name %>
    </div>
    <div class="spot-name"><%= @spot.name %></div>
    <div class="spot-image"><%= image_tag(@spot.photo, width: '350px', class:"image") %></div>
    <div class="spot-textarea"><%= simple_format @spot.value,width: '100%' %></div>
    <div class="spot-url"><%= link_to @spot.spots_url, @spot.spots_url %></div>
    <div class="">投稿者: <%= link_to(@spot.user.nickname,"/users/#{@spot.user.id}") %></div>
  <% end %>

  <div class="geolonia"
    data-lat=<%= @spot.lat %>
    data-lng=<%= @spot.lng %>
    data-zoom=16
    style="height:350px;"><%= marker_content(@spot) %></div>

  <div class="btn-toolbar">
    <%if user_signed_in? && current_user.id == @spot.user_id %>
      <%= link_to "編集", edit_spot_path(@spot), data: {turbo: false}, class: "btn btn-primary" %>
      <%= button_to "投稿削除", @spot, method: :delete, class: "btn btn-danger ms-3" %>
    <% end %>
  </div>


  <script type="text/javascript" src="https://cdn.geolonia.com/v1/embed?geolonia-api-key=<%= ENV['MAP_API_KEY'] %>"></script>
</div>

  <%= link_to(root_path,class: "purchase-btn") do %>
    <span class="purchase-btn-text">HOMEへ</span>
    <%= image_tag "home.png", size: "185x50", class: "purchase-btn-icon" %>
  <% end %>